# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: Shared/proto/api.proto, Shared/proto/common.proto
# plugin: python-betterproto2
# This file has been @generated

__all__ = (
    "Event",
    "SimpleResponse",
    "UserLoggedIn",
)

from dataclasses import dataclass

import betterproto2

from ...message_pool import default_message_pool

_COMPILER_VERSION = "0.9.0"
betterproto2.check_compiler_version(_COMPILER_VERSION)


@dataclass(eq=False, repr=False)
class Event(betterproto2.Message):
    function_name: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    payload: "__google__protobuf__.Any | None" = betterproto2.field(
        2, betterproto2.TYPE_MESSAGE, optional=True
    )


default_message_pool.register_message("holybot.api", "Event", Event)


@dataclass(eq=False, repr=False)
class SimpleResponse(betterproto2.Message):
    success: "bool" = betterproto2.field(1, betterproto2.TYPE_BOOL)

    message: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)


default_message_pool.register_message("holybot.api", "SimpleResponse", SimpleResponse)


@dataclass(eq=False, repr=False)
class UserLoggedIn(betterproto2.Message):
    user_id: "str" = betterproto2.field(1, betterproto2.TYPE_STRING)

    code: "str" = betterproto2.field(2, betterproto2.TYPE_STRING)

    redirect_uri: "str" = betterproto2.field(3, betterproto2.TYPE_STRING)


default_message_pool.register_message("holybot.api", "UserLoggedIn", UserLoggedIn)


from ...google import protobuf as __google__protobuf__
