# Auto-generated stubs
# DO NOT EDIT THIS FILE
# Implementation are in the microservice.py

from holybot_shared.communicator.microservice import Microservice
import holybot_shared.SharedProto.holybot.api


class API(Microservice):
    async def test(self, payload: holybot_shared.SharedProto.holybot.api.UserLoggedIn, *, timeout: int = 10) -> holybot_shared.SharedProto.holybot.api.SimpleResponse:
        ...

    async def recheck_tokens(self) -> None:
        ...

    async def get_token(self, payload: holybot_shared.SharedProto.holybot.api.UserLoggedIn, *, timeout: int = 10) -> holybot_shared.SharedProto.holybot.api.SimpleResponse:
        ...
