"""add user_id to session and twitch_token

Revision ID: 59a3f2b1d7e2
Revises: bdcc9bea8fb5
Create Date: 2026-01-24 01:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59a3f2b1d7e2'
down_revision: Union[str, Sequence[str], None] = 'bdcc9bea8fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_session_user_id', 'session', 'user', ['user_id'], ['id'])
    op.add_column('twitch_token', sa.Column('user_id', sa.Uuid(), nullable=False))
    op.create_foreign_key('fk_twitch_token_user_id', 'twitch_token', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_twitch_token_user_id', 'twitch_token', type_='foreignkey')
    op.drop_column('twitch_token', 'user_id')
    op.drop_constraint('fk_session_user_id', 'session', type_='foreignkey')
    op.drop_column('session', 'user_id')
    # ### end Alembic commands ###
